---
abstract: 'Convert Dia class diagrams into SQL.'
author:
  - 'Andreas Faafeng <aff@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
keywords:
  - Parse
  - Dia
  - SQL
  - DDL
  - RDBMS
  - DB2
  - Informix
  - Ingres
  - InnoDB
  - MyISAM
  - MySQL
  - Oracle
  - Postgres
  - SQLite3
  - Sas
  - Sybase
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Parse-Dia-SQL
no_index:
  directory:
    - t
    - inc
requires:
  Data::Dumper: 0
  Digest::MD5: 0
  Fatal: 0
  File::Find: 0
  File::Spec::Functions: 0
  File::Temp: 0
  Getopt::Long: 0
  IO::Uncompress::Gunzip: 0
  Log::Log4perl: 0
  POSIX: 0
  Test::Exception: 0
  Test::More: 0
  Text::Table: 0
  XML::DOM: 0
resources:
  repository: http://tedia2sql.tigris.org/source/browse/tedia2sql/
version: 0.20
